version: '3'
services:
  java-srv:
    build: py-srv
    command: sh -c "/wait && python app.py"
    environment:
      - WAIT_HOSTS=hbase:9090
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30

  hbase:
    image: dajobe/hbase
    hostname: hbase-docker
    ports:
     - 9090
